### ISSUE TITLE
Changes to Videos UI to keep it consistent with Dega

### ISSUE THREAD

**Issue by deshetti** [factly/vidcheck#23]
Add the following fields to video entity to keep it consistent with claim in Dega:
- [x] Claimant - Dependent on the issue: https://github.com/factly/vidcheck/issues/21
- [x] Claim Date - Dependent on the issue: https://github.com/factly/vidcheck/issues/22
- [x] Checked Date - Dependent on the issue: https://github.com/factly/vidcheck/issues/22

Label changes
- [x] Change the label from `Fact check` to `Fact`

Following issues are dependent on https://github.com/factly/vidcheck/issues/24
- [x] Change `Review Sources` to the component: https://ant.design/components/form/#components-form-demo-dynamic-form-items. Add the following group of fields:
- URL
- Description
- [x] Change `Claim` to EditorJS component
- [x] Change `Fact` to EditorJS component
- [x] Save the video URL with the start and end times as the claim_source automatically. Don't have to display this on the UI
